disable-version-string: true
resolve-type-alias: false
with-expecter: true
mock-build-tags: "!compile"
inpackage: true
issue-845-fix: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ksysoev/anycache:
    interfaces:
      CacheStorage:
