// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package anycache

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockCacheStorage is an autogenerated mock type for the CacheStorage type
type MockCacheStorage struct {
	mock.Mock
}

type MockCacheStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheStorage) EXPECT() *MockCacheStorage_Expecter {
	return &MockCacheStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockCacheStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCacheStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCacheStorage_Expecter) Close() *MockCacheStorage_Close_Call {
	return &MockCacheStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCacheStorage_Close_Call) Run(run func()) *MockCacheStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheStorage_Close_Call) Return(_a0 error) *MockCacheStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheStorage_Close_Call) RunAndReturn(run func() error) *MockCacheStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Del provides a mock function with given fields: _a0, _a1
func (_m *MockCacheStorage) Del(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheStorage_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockCacheStorage_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockCacheStorage_Expecter) Del(_a0 interface{}, _a1 interface{}) *MockCacheStorage_Del_Call {
	return &MockCacheStorage_Del_Call{Call: _e.mock.On("Del", _a0, _a1)}
}

func (_c *MockCacheStorage_Del_Call) Run(run func(_a0 context.Context, _a1 string)) *MockCacheStorage_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheStorage_Del_Call) Return(_a0 bool, _a1 error) *MockCacheStorage_Del_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheStorage_Del_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCacheStorage_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MockCacheStorage) Get(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockCacheStorage_Expecter) Get(_a0 interface{}, _a1 interface{}) *MockCacheStorage_Get_Call {
	return &MockCacheStorage_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *MockCacheStorage_Get_Call) Run(run func(_a0 context.Context, _a1 string)) *MockCacheStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheStorage_Get_Call) Return(_a0 string, _a1 error) *MockCacheStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheStorage_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCacheStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithTTL provides a mock function with given fields: _a0, _a1
func (_m *MockCacheStorage) GetWithTTL(_a0 context.Context, _a1 string) (string, time.Duration, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetWithTTL")
	}

	var r0 string
	var r1 time.Duration
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, time.Duration, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) time.Duration); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCacheStorage_GetWithTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithTTL'
type MockCacheStorage_GetWithTTL_Call struct {
	*mock.Call
}

// GetWithTTL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockCacheStorage_Expecter) GetWithTTL(_a0 interface{}, _a1 interface{}) *MockCacheStorage_GetWithTTL_Call {
	return &MockCacheStorage_GetWithTTL_Call{Call: _e.mock.On("GetWithTTL", _a0, _a1)}
}

func (_c *MockCacheStorage_GetWithTTL_Call) Run(run func(_a0 context.Context, _a1 string)) *MockCacheStorage_GetWithTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheStorage_GetWithTTL_Call) Return(_a0 string, _a1 time.Duration, _a2 error) *MockCacheStorage_GetWithTTL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCacheStorage_GetWithTTL_Call) RunAndReturn(run func(context.Context, string) (string, time.Duration, error)) *MockCacheStorage_GetWithTTL_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockCacheStorage) Set(_a0 context.Context, _a1 string, _a2 string, _a3 time.Duration) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 time.Duration
func (_e *MockCacheStorage_Expecter) Set(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockCacheStorage_Set_Call {
	return &MockCacheStorage_Set_Call{Call: _e.mock.On("Set", _a0, _a1, _a2, _a3)}
}

func (_c *MockCacheStorage_Set_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 time.Duration)) *MockCacheStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCacheStorage_Set_Call) Return(_a0 error) *MockCacheStorage_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheStorage_Set_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockCacheStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}

// TTL provides a mock function with given fields: _a0, _a1
func (_m *MockCacheStorage) TTL(_a0 context.Context, _a1 string) (bool, time.Duration, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 bool
	var r1 time.Duration
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, time.Duration, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) time.Duration); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCacheStorage_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type MockCacheStorage_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockCacheStorage_Expecter) TTL(_a0 interface{}, _a1 interface{}) *MockCacheStorage_TTL_Call {
	return &MockCacheStorage_TTL_Call{Call: _e.mock.On("TTL", _a0, _a1)}
}

func (_c *MockCacheStorage_TTL_Call) Run(run func(_a0 context.Context, _a1 string)) *MockCacheStorage_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheStorage_TTL_Call) Return(_a0 bool, _a1 time.Duration, _a2 error) *MockCacheStorage_TTL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCacheStorage_TTL_Call) RunAndReturn(run func(context.Context, string) (bool, time.Duration, error)) *MockCacheStorage_TTL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheStorage creates a new instance of MockCacheStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheStorage {
	mock := &MockCacheStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
