version: "3.8"

services:
  tests:
    build: ./
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go test -race -v ./...
    environment:
      - TEST_REDIS_HOST=redis
      - TEST_REDIS_PORT=6379
      - TEST_MEMCACHED_HOST=memcached
      - TEST_MEMCACHED_PORT=11211
    depends_on:
      - redis
      - memcached
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379"
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211"
