// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package memcache

import (
	gomemcachememcache "github.com/bradfitz/gomemcache/memcache"
	mock "github.com/stretchr/testify/mock"
)

// MockMemCached is an autogenerated mock type for the MemCached type
type MockMemCached struct {
	mock.Mock
}

type MockMemCached_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemCached) EXPECT() *MockMemCached_Expecter {
	return &MockMemCached_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: key
func (_m *MockMemCached) Delete(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemCached_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMemCached_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *MockMemCached_Expecter) Delete(key interface{}) *MockMemCached_Delete_Call {
	return &MockMemCached_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockMemCached_Delete_Call) Run(run func(key string)) *MockMemCached_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMemCached_Delete_Call) Return(_a0 error) *MockMemCached_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemCached_Delete_Call) RunAndReturn(run func(string) error) *MockMemCached_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockMemCached) Get(key string) (*gomemcachememcache.Item, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *gomemcachememcache.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*gomemcachememcache.Item, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *gomemcachememcache.Item); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gomemcachememcache.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemCached_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMemCached_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockMemCached_Expecter) Get(key interface{}) *MockMemCached_Get_Call {
	return &MockMemCached_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockMemCached_Get_Call) Run(run func(key string)) *MockMemCached_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMemCached_Get_Call) Return(_a0 *gomemcachememcache.Item, _a1 error) *MockMemCached_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemCached_Get_Call) RunAndReturn(run func(string) (*gomemcachememcache.Item, error)) *MockMemCached_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: item
func (_m *MockMemCached) Set(item *gomemcachememcache.Item) error {
	ret := _m.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gomemcachememcache.Item) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemCached_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockMemCached_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - item *gomemcachememcache.Item
func (_e *MockMemCached_Expecter) Set(item interface{}) *MockMemCached_Set_Call {
	return &MockMemCached_Set_Call{Call: _e.mock.On("Set", item)}
}

func (_c *MockMemCached_Set_Call) Run(run func(item *gomemcachememcache.Item)) *MockMemCached_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gomemcachememcache.Item))
	})
	return _c
}

func (_c *MockMemCached_Set_Call) Return(_a0 error) *MockMemCached_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemCached_Set_Call) RunAndReturn(run func(*gomemcachememcache.Item) error) *MockMemCached_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemCached creates a new instance of MockMemCached. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemCached(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemCached {
	mock := &MockMemCached{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
