// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package redis

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	v9 "github.com/redis/go-redis/v9"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, keys
func (_m *MockClient) Del(ctx context.Context, keys ...string) *v9.IntCmd {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 *v9.IntCmd
	if rf, ok := ret.Get(0).(func(context.Context, ...string) *v9.IntCmd); ok {
		r0 = rf(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v9.IntCmd)
		}
	}

	return r0
}

// MockClient_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockClient_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockClient_Expecter) Del(ctx interface{}, keys ...interface{}) *MockClient_Del_Call {
	return &MockClient_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockClient_Del_Call) Run(run func(ctx context.Context, keys ...string)) *MockClient_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Del_Call) Return(_a0 *v9.IntCmd) *MockClient_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Del_Call) RunAndReturn(run func(context.Context, ...string) *v9.IntCmd) *MockClient_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockClient) Get(ctx context.Context, key string) *v9.StringCmd {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v9.StringCmd
	if rf, ok := ret.Get(0).(func(context.Context, string) *v9.StringCmd); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v9.StringCmd)
		}
	}

	return r0
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) Get(ctx interface{}, key interface{}) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockClient_Get_Call) Run(run func(ctx context.Context, key string)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(_a0 *v9.StringCmd) *MockClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(context.Context, string) *v9.StringCmd) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// PTTL provides a mock function with given fields: ctx, key
func (_m *MockClient) PTTL(ctx context.Context, key string) *v9.DurationCmd {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for PTTL")
	}

	var r0 *v9.DurationCmd
	if rf, ok := ret.Get(0).(func(context.Context, string) *v9.DurationCmd); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v9.DurationCmd)
		}
	}

	return r0
}

// MockClient_PTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PTTL'
type MockClient_PTTL_Call struct {
	*mock.Call
}

// PTTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockClient_Expecter) PTTL(ctx interface{}, key interface{}) *MockClient_PTTL_Call {
	return &MockClient_PTTL_Call{Call: _e.mock.On("PTTL", ctx, key)}
}

func (_c *MockClient_PTTL_Call) Run(run func(ctx context.Context, key string)) *MockClient_PTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_PTTL_Call) Return(_a0 *v9.DurationCmd) *MockClient_PTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_PTTL_Call) RunAndReturn(run func(context.Context, string) *v9.DurationCmd) *MockClient_PTTL_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *MockClient) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *v9.StatusCmd {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *v9.StatusCmd
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) *v9.StatusCmd); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v9.StatusCmd)
		}
	}

	return r0
}

// MockClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *MockClient_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockClient_Set_Call {
	return &MockClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockClient_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *MockClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockClient_Set_Call) Return(_a0 *v9.StatusCmd) *MockClient_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) *v9.StatusCmd) *MockClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
