// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v7.35.0
// source: storage/memcache/proto/cached_item.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CachedItem wraps a cache value together with an optional absolute
// expiry timestamp so that TTL can be recovered on read-back.
// When expires_at_unix == 0 the item has no expiration.
type CachedItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw cache value.
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Absolute expiry as Unixtime(0 = no expiration).
	ExpiresAtUnix int64 `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
}

func (x *CachedItem) Reset() {
	*x = CachedItem{}
	mi := &file_storage_memcache_proto_cached_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedItem) ProtoMessage() {}

func (x *CachedItem) ProtoReflect() protoreflect.Message {
	mi := &file_storage_memcache_proto_cached_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedItem.ProtoReflect.Descriptor instead.
func (*CachedItem) Descriptor() ([]byte, []int) {
	return file_storage_memcache_proto_cached_item_proto_rawDescGZIP(), []int{0}
}

func (x *CachedItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CachedItem) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_storage_memcache_proto_cached_item_proto protoreflect.FileDescriptor

var file_storage_memcache_proto_cached_item_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x6d, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f,
	0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x6d, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x22, 0x4a, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x73, 0x79, 0x73, 0x6f, 0x65, 0x76, 0x2f, 0x61, 0x6e, 0x79, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_memcache_proto_cached_item_proto_rawDescOnce sync.Once
	file_storage_memcache_proto_cached_item_proto_rawDescData = file_storage_memcache_proto_cached_item_proto_rawDesc
)

func file_storage_memcache_proto_cached_item_proto_rawDescGZIP() []byte {
	file_storage_memcache_proto_cached_item_proto_rawDescOnce.Do(func() {
		file_storage_memcache_proto_cached_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_memcache_proto_cached_item_proto_rawDescData)
	})
	return file_storage_memcache_proto_cached_item_proto_rawDescData
}

var file_storage_memcache_proto_cached_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storage_memcache_proto_cached_item_proto_goTypes = []any{
	(*CachedItem)(nil), // 0: memcache.CachedItem
}
var file_storage_memcache_proto_cached_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_memcache_proto_cached_item_proto_init() }
func file_storage_memcache_proto_cached_item_proto_init() {
	if File_storage_memcache_proto_cached_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_memcache_proto_cached_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_memcache_proto_cached_item_proto_goTypes,
		DependencyIndexes: file_storage_memcache_proto_cached_item_proto_depIdxs,
		MessageInfos:      file_storage_memcache_proto_cached_item_proto_msgTypes,
	}.Build()
	File_storage_memcache_proto_cached_item_proto = out.File
	file_storage_memcache_proto_cached_item_proto_rawDesc = nil
	file_storage_memcache_proto_cached_item_proto_goTypes = nil
	file_storage_memcache_proto_cached_item_proto_depIdxs = nil
}
